trigger:
  branches:
    include:
      - main
 
pool:
  name: 'TerraformRun'
 
jobs:
- job: TerraformExecution
  steps:
    - script: |
        echo "Extracting Repository Name for Terraform Backend..."
        set REPO_NAME=%BUILD_REPOSITORY_NAME%
        echo REPO_NAME is %REPO_NAME%
      displayName: 'Extract Repository Name for Terraform Backend'
    
    - script: |
        echo "List files in Work dir"
        dir
      displayName: "list Files in Directroy"
 
    # Step 4: Initialize Terraform Backend with Azure Storage Account and Managed Identity
    - script: |
        cd $(Build.SourcesDirectory)
        terraform init ^
          -backend-config="storage_account_name=gchstoreusptistrf01" ^
          -backend-config="container_name=tfstatepo" ^
          -backend-config="key=%BUILD_REPOSITORY_NAME%/terraform.tfstate" ^
          -backend-config="use_msi=true" ^
          -backend-config="resource_group_name=gch-rg-eus-prod-terraform-01" ^
          -backend-config="subscription_id=de52f15e-9c68-4673-b173-9de91aa89657" ^
          -backend-config="tenant_id=958a7efb-f2a7-4ea2-80ee-85fc8ed01be7"
      workingDirectory: $(Build.SourcesDirectory)
      displayName: 'Initialize Terraform Backend'
 
    # Step 5: Validate Terraform Configuration
    - script: terraform validate
      displayName: 'Validate Terraform Configuration'
 
    # Step 6: Generate Terraform Plan
    - script: terraform plan -out=tfplan -input=false
      displayName: 'Generate and Save Terraform Plan'
 
    # Step 7: Apply the Terraform Plan
    - script: terraform apply -auto-approve tfplan
      displayName: 'Terraform Apply'